const data = `——————————————————————————
Dance Music: DJ Cassidy, R. Kelly, Robin Thicke
This catalog includes dance songs from popular DJ Cassidy, featuring R. Kelly, Robin Thicke, Nile Rodgers, Jessie J, and a newly released track that has not yet received its first royalty payment!
https://auctions.royaltyexchange.com/asset_file/3fbe5ee15b5fd078fd9ff5b72f3cbd2d/Dj%20Cassidy.png
https://auctions.royaltyexchange.com/auctions/dance-music-dj-cassidy-r-kelly-robin-thicke/?origin=listings&filter_value=listings
——————————————————————————
R&B From Babyface
Collect royalties from this R&B catalog highlighted by singles from the 11-time Grammy winner Babyface and more.
https://auctions.royaltyexchange.com/asset_file/dbf7b0b60215c7f1961b5a6527f2807e/Babyface.png
https://auctions.royaltyexchange.com/auctions/rb-from-babyface/?origin=listings&filter_value=listings
——————————————————————————
Huge Catalog of Covers & Instrumentals
Earn 25% of digital download and streaming royalties for a catalog of sound recordings. This catalog includes covers of popular American and Latin music, as well as instrumentals, karaoke, and background tracks.
https://auctions.royaltyexchange.com/asset_file/d88e00b8d665f7f5c8e79a07b29207b8/8442794.jpg
https://auctions.royaltyexchange.com/auctions/huge-catalog-of-covers-instrumentals-1/?origin=listings&filter_value=listings
——————————————————————————
Production Music Used In Sports, Cable, Reality TV
Boasting 13 years of earnings, this catalog contains music used across NBA & NHL sportscasts, network and cable series and reality TV shows.
https://auctions.royaltyexchange.com/asset_file/08045d228cfe623889f31181141ad8a9/ProducationMusicCatalog.png
https://auctions.royaltyexchange.com/auctions/production-music-used-in-sports-cable-reality-tv/?origin=listings&filter_value=listings
——————————————————————————
70s Soft Rock: “Sharing The Night Together”
This catalog earns songwriter and publisher royalties from the popular 1978 hit “Sharing The Night Together” from Dr. Hook and more.
https://auctions.royaltyexchange.com/asset_file/125f8efb430270c031c2b835723275f9/SharingTheNighttogether.png
https://auctions.royaltyexchange.com/auctions/70s-soft-rock-sharing-the-night-together/?origin=listings&filter_value=listings
——————————————————————————
Akon's 3x Platinum Hit “Don't Matter”
Invest in growing royalties generated by the triple Platinum-certified track “Don't Matter,” from Grammy-nominated artist Akon.
https://auctions.royaltyexchange.com/asset_file/20e6fadc4c690206baf1e4f1de9f1699/AKON.png
https://auctions.royaltyexchange.com/auctions/akons-3x-platinum-hit-dont-matter/?origin=listings&filter_value=listings
——————————————————————————
Recent Hip-Hop Hit
This single song auction is for the royalties generated by the viral hit “Ran Off On Da Plug Twice” featuring hip-hop artist Plies.
https://auctions.royaltyexchange.com/asset_file/1957a7a9d49e84e327ccc27cf7a99287/plies%20(1).png
https://auctions.royaltyexchange.com/auctions/recent-hip-hop-hit/?origin=listings&filter_value=state&state=closed
——————————————————————————
Platinum Pop Hit "Replay" and More
Earn publisher royalties from a collection of music highlighted by pop princess Zendaya, Grammy-winner Jennifer Hudson, American Idol's La'Porsha Renae and more.
https://auctions.royaltyexchange.com/asset_file/fb832e8503748cc9ca385b19820a4650/Zendaya.png
https://auctions.royaltyexchange.com/auctions/platinum-pop-hit-replay-and-more/?origin=listings&filter_value=state&state=closed
——————————————————————————
Alternative Metal Sound
Collect sales and streaming royalties generated by the post-hardcore band Outline In Color.
https://auctions.royaltyexchange.com/asset_file/1e1d71109cc6947bbbbb4967da747e9b/500x500%20(1).jpg
https://auctions.royaltyexchange.com/auctions/alternative-metal-sound-recording-royalties/?origin=listings&filter_value=state&state=closed
——————————————————————————
Popular Christian Worship Music
Here's an opportunity to earn royalties from time-honored Christian music with diverse income sources.
https://auctions.royaltyexchange.com/asset_file/2a9358b68dcb04f52a081758b3df6481/popchrist%20(1).png
https://auctions.royaltyexchange.com/auctions/popular-christian-worship-music/?origin=listings&filter_value=state&state=closed
——————————————————————————
Indie Rock Sound Recording
Invest in sound recording royalties generated by the indie rock group From Indian Lakes.
https://auctions.royaltyexchange.com/asset_file/e7d0d8b70b6c4378084fc07e4f20032e/FromIndianLakes.png
https://auctions.royaltyexchange.com/auctions/indie-rock-sound-recording-royalties/?origin=listings&filter_value=state&state=closed
——————————————————————————
Music In “Deadpool,” “Old School” & More
Collect royalties from a diverse catalog with music featured in Golden Globe-nominated Deadpool, Disney's Ice Princess, Will Farrell's Old School, hot reality TV shows and much more!
https://auctions.royaltyexchange.com/asset_file/7164b6e64fd5bca1aaa04aed6f95c2db/Deadpool2%20(1).png
https://auctions.royaltyexchange.com/auctions/music-in-deadpool-old-school-more/?origin=listings&filter_value=state&state=closed
——————————————————————————
Santana's "No One To Depend On"
Collect royalties from the 1972 single “No One To Depend On,” from the legendary Latin band, Santana!
https://auctions.royaltyexchange.com/asset_file/d30482cda968d43ccb8b5218ad47c660/santana.png
https://auctions.royaltyexchange.com/auctions/santanas-no-one-to-depend-on/?origin=listings&filter_value=state&state=closed
——————————————————————————
Music Used In Popular Reality TV Shows
Earn public performance royalties from popular reality TV shows including Real Housewives of Beverly Hills, Vanderpump Rules, Top Chef and more!
https://auctions.royaltyexchange.com/asset_file/6943130fac0041a241413860c35a003c/musicfrom.png
https://auctions.royaltyexchange.com/auctions/music-used-in-popular-reality-tv-shows/?origin=listings&filter_value=state&state=closed
——————————————————————————
Theme Music: "In Touch Ministries"
This catalog features growing royalties from theme music used in the long-running TV series, In Touch with Dr. Charles Stanley.
https://auctions.royaltyexchange.com/asset_file/dfba5cd07273c0814ffd32451ab2c792/nomatterwherewe%20are.png
https://auctions.royaltyexchange.com/auctions/theme-music-in-touch-ministries-1/?origin=listings&filter_value=state&state=closed
——————————————————————————
R&B and Pop Music With Global Earnings
Collect 72% of public performance royalties from a diverse catalog of music that ranges from R&B to K-Pop and collects income in over 50 countries.
https://auctions.royaltyexchange.com/asset_file/f7c2dde452cf28f4d4f8d40a71929c28/R&Bpopcatalog.png
https://auctions.royaltyexchange.com/auctions/rb-and-pop-music-with-global-earnings-1/?origin=listings&filter_value=state&state=closed
——————————————————————————
Indie Pop Used in "New Girl" & More
Invest in this catalog from a multifaceted musician whose tracks have been featured in popular sitcoms on network TV.
https://auctions.royaltyexchange.com/asset_file/fdb032c2db20090667767258599f3e7e/IndiePopMusic.png
https://auctions.royaltyexchange.com/auctions/indie-pop-used-in-new-girl-more/?origin=listings&filter_value=state&state=closed
——————————————————————————
Music Used In Sports, Reality & Cable TV Shows
With annually earnings growing since 2010, this catalog contains placements across NBA and NHL programming, hot reality TV series and popular network/cable programs.
https://auctions.royaltyexchange.com/asset_file/adc2b024019bcf07de17ac806ad7c31f/Sports.png
https://auctions.royaltyexchange.com/auctions/music-used-in-sports-reality-cable-tv-shows/?origin=listings&filter_value=state&state=closed
——————————————————————————
Songs from Mutemath's Back Catalog
Earn public performance royalties for a catalog of music including songs by the alternative rock band Mutemath.
https://auctions.royaltyexchange.com/asset_file/bbc1aae5b9a878a890c8a8432f50ccc0/Mutemath.png
https://auctions.royaltyexchange.com/auctions/songs-from-mutemaths-back-catalog/?origin=listings&filter_value=state&state=closed
——————————————————————————
Hip-Hop Catalog, Featuring T.I.
Collect royalties from this hip-hop catalog featuring “ASAP” from T.I., plus tracks from LL Cool J with R Kelly, Trick Daddy, Akon and many more.
https://auctions.royaltyexchange.com/asset_file/55756c38dbedb2a407bcda5a31856ecb/HipHopCatalogft%20(2).png
https://auctions.royaltyexchange.com/auctions/hip-hop-catalog-featuring-ti/?origin=listings&filter_value=state&state=closed
——————————————————————————
Pop Hits: Ariana Grande, Chris Brown, J.Lo
Growing royalties from some of the biggest names in pop music: Chris Brown, Meghan Trainor, Ariana Grande featuring Lil Wayne and Jennifer Lopez!
https://auctions.royaltyexchange.com/asset_file/dbe4ffd0dac33bd3faf356a23507eecb/CatalogPop.png
https://auctions.royaltyexchange.com/auctions/pop-hits-ariana-grande-chris-brown-jlo/?origin=listings&filter_value=state&state=closed`.split('\n')

export const logos = data.filter((v, i) => (i % 5) - 3 === 0)
export const names = data.filter((v, i) => (i % 5) - 1 === 0)
export const progress = Array(names.length).fill(0).map(() => Math.floor(Math.random() * 10000))
